"""Generate the project notebooks.

Notebooks are *generated* rather than hand-edited for the same reason the results
table is: a notebook that is edited in place accumulates hidden state, stale
outputs and cells that only ran once in an order nobody recorded. Regenerating
from this script guarantees the committed notebooks are exactly what the source
says, with no execution counts or outputs baked in.

    python scripts/build_notebooks.py

Both notebooks are **thin drivers** (docs/06 §1): they install the package and
call its API. No model code lives in a cell, because code in a notebook cannot
be tested, reviewed, or re-run six weeks later.
"""

from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[1] / "notebooks"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines) -> list[str]:
    text = "\n".join(lines)
    out = text.splitlines(keepends=True)
    return out or [""]


def notebook(cells: list[dict], *, accelerator: str = "none") -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
            "accelerator": "GPU" if accelerator == "gpu" else "None",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


# ===========================================================================
# 01 — laptop: acquisition, audit, EDA, Tier 0
# ===========================================================================

LAPTOP = [
    md(
        "# 01 — Data acquisition, audit and exploratory analysis (laptop)",
        "",
        "Runs on the RTX 3050 laptop (4 GB VRAM). Everything here is either CPU-bound or",
        "small enough to fit the card. The heavy sweeps live in `02_kaggle_experiments.ipynb`.",
        "",
        "**What this notebook decides:** the input resolution for the study. That single",
        "choice determines whether the experiments measure the *method* or measure the",
        "*resize* — see [docs/10-datasets.md](../docs/10-datasets.md) and",
        "[docs/01-charter-and-protocol.md](../docs/01-charter-and-protocol.md) §4.1.",
        "",
        "**Order matters.** Fit is never called before the split audit passes. A leaked",
        "split does not raise an error, it produces a *better* score, so it has to be",
        "ruled out mechanically before any number is generated.",
        "",
        "---",
        "",
        "Dataset: **VisA** (Amazon), CC BY 4.0. No images are redistributed by this",
        "repository. Attribution in [ATTRIBUTION.md](../ATTRIBUTION.md).",
    ),
    md("## 0. Environment"),
    code(
        "import sys, subprocess, pathlib",
        "",
        "REPO = pathlib.Path.cwd()",
        "if not (REPO / 'src' / 'inspector').exists():",
        "    REPO = REPO.parent  # running from notebooks/",
        "sys.path.insert(0, str(REPO / 'src'))",
        "",
        "from inspector.utils.env import capture",
        "",
        "env = capture()",
        "print('git      :', env['git_sha'], '(dirty)' if env['dirty'] else '(clean)')",
        "print('device   :', env['device'].get('gpu_name', 'CPU only'),",
        "      f\"{env['device'].get('gpu_total_mb', 0)} MB\")",
        "print('torch    :', env['libraries'].get('torch', 'not installed'))",
        "print()",
        "print('A dirty tree tags every run dirty, and dirty runs may not enter the')",
        "print('headline table (docs/06 section 2). Commit before a reportable run.')",
    ),
    md(
        "## 1. Acquire VisA",
        "",
        "1.8 GB over HTTPS, no account. The fetch records a SHA-256 manifest so a",
        "silently truncated or updated archive is detected rather than trained on.",
    ),
    code(
        "from inspector.fetch import fetch, verify",
        "",
        "DATA_RAW = REPO / 'data' / 'raw'",
        "manifest = fetch('visa', DATA_RAW, extract=True)",
        "",
        "VISA_ROOT = pathlib.Path(manifest.extracted_to)",
        "print('root     :', VISA_ROOT)",
        "print('action   :', manifest.action)",
        "for name, digest in manifest.files.items():",
        "    print(f'  {name:26s} sha256={digest[:16]}')",
        "print()",
        "print('license  :', manifest.license_note)",
    ),
    code(
        "# Re-run this after any sync to Drive or Kaggle. Sync corruption is silent,",
        "# and finding it a week later costs a week.",
        "for name, ok in verify('visa', DATA_RAW).items():",
        "    print(f\"  {'OK  ' if ok else 'FAIL'} {name}\")",
    ),
    md(
        "## 2. The official one-class split",
        "",
        "`split_csv/1cls.csv` is authoritative. Inventing a split would produce numbers",
        "comparable with nothing, so the loader treats a missing CSV as an error rather",
        "than falling back on directory scanning.",
    ),
    code(
        "from inspector.data.visa import VISA_GROUPS, summarize",
        "from inspector.postproc import min_achievable_fpr",
        "",
        "counts = summarize(VISA_ROOT)",
        "print(f\"{'category':<13}{'group':<20}{'train':>7}{'test_N':>8}{'test_A':>8}\"",
        "      f\"{'val@15%':>9}{'minFPR':>8}\")",
        "print('-' * 73)",
        "for cat, c in counts.items():",
        "    n_val = max(4, round(c['train_normal'] * 0.15))",
        "    print(f\"{cat:<13}{c['group']:<20}{c['train_normal']:>7}{c['test_normal']:>8}\"",
        "          f\"{c['test_anomaly']:>8}{n_val:>9}{min_achievable_fpr(n_val):>7.2%}\")",
    ),
    md(
        "### Read the `minFPR` column",
        "",
        "A threshold set as the k-th largest of `n` validation scores is exceeded by a",
        "fresh normal sample with probability `k/(n+1)`, so the achievable false-alarm",
        "floor is `1/(n+1)` — see [ADR-7](../docs/07-risks-and-decisions.md).",
        "",
        "On VisA that floor lands **on both sides of 1%**: the large categories",
        "(`candle`, `macaroni*`, `pcb*`) can be calibrated to 1%, the small ones",
        "(`cashew`, `fryum`, `chewinggum`, `pipe_fryum`) cannot. The same protocol is",
        "therefore achievable on some categories and not others *within one dataset*,",
        "which is why the operating point is reported per category rather than as one",
        "headline FPR.",
        "",
        "The floor depends on the 15% carve fraction, which is our choice, not VisA's.",
        "Raising it buys a lower floor at the cost of training images — an ablation worth",
        "running rather than a default worth assuming.",
    ),
    md(
        "## 3. Study categories",
        "",
        "One from each of VisA's three structural groups, so each fails for a different",
        "reason. Three PCBs would test one difficulty three times.",
        "",
        "| category | group | axis it stresses |",
        "|---|---|---|",
        "| `pcb1` | complex structure | resolution / small defects |",
        "| `macaroni2` | multiple instances | false positives from normal variation |",
        "| `capsules` | multiple instances | optics: transparent, reflective |",
    ),
    code(
        "CATEGORIES = ['pcb1', 'macaroni2', 'capsules']",
        "CONTROL = 'cashew'  # easiest group; a method that fails here is broken",
        "",
        "from inspector.data import ensure_validation, load_category",
        "",
        "indices = {}",
        "for cat in CATEGORIES:",
        "    idx = load_category(VISA_ROOT, cat, layout='visa')",
        "    idx, assignment = ensure_validation(idx, val_fraction=0.15, seed=0)",
        "    indices[cat] = idx",
        "    print(f'{cat:<11} ' + '  '.join(",
        "        f'{k}={len(v)}(N{v.n_normal}/A{v.n_anomalous})' for k, v in sorted(idx.items())))",
        "    if assignment:",
        "        print(f'{\"\":<11} validation carved from train, seed={assignment.seed} '",
        "              f'digest={assignment.digest[:12]}')",
    ),
    md(
        "## 4. Split integrity — run before anything is fitted",
        "",
        "Protocol rules L1-L7. L1 compares SHA-256 of file **bytes**, not filenames: the",
        "failure mode that matters is the same capture appearing in two splits under",
        "different names, which a filename check would miss entirely.",
    ),
    code(
        "from inspector.data.integrity import audit",
        "",
        "all_ok = True",
        "for cat, idx in indices.items():",
        "    print(f'--- {cat} ---')",
        "    for report in audit(idx):",
        "        print(' ', report)",
        "        all_ok &= report.ok",
        "",
        "assert all_ok, 'split integrity failed: fix before generating any number'",
        "print('\\nall integrity checks passed')",
    ),
    md(
        "## 5. Exploratory analysis — the resolution decision",
        "",
        "Measures every connected defect region, then computes what each candidate",
        "resolution does to the **smallest** defects. The percentiles matter more than",
        "the median here: the median defect is rarely the one a model misses.",
    ),
    code(
        "from inspector.eda import analyse_category",
        "from inspector.report import write_eda_report",
        "",
        "CANDIDATES = (128, 224, 256, 320, 448, 512)",
        "reports = []",
        "for cat, idx in indices.items():",
        "    print(f'analysing {cat} ...')",
        "    reports.append(analyse_category(idx, test_split='test', candidates=CANDIDATES))",
        "",
        "md_path, json_path = write_eda_report(reports, REPO / 'reports' / 'eda_visa')",
        "print('\\nreport ->', md_path)",
    ),
    code(
        "for r in reports:",
        "    s = r.region_summary",
        "    print(f'=== {r.category}  native {r.native_size[0]}x{r.native_size[1]} '",
        "          f'({r.aspect_ratio:.2f}:1) ===')",
        "    print(f'  regions            : {int(s[\"n_regions\"])} over {int(s[\"n_images\"])} images')",
        "    print(f'  area %% of image    : p1 {s[\"area_fraction_p1\"]:.4%}  '",
        "          f'median {s[\"area_fraction_median\"]:.4%}  max {s[\"area_fraction_max\"]:.3%}')",
        "    print(f'  thin dimension px  : p1 {s[\"min_extent_p1\"]:.1f}  median {s[\"min_extent_median\"]:.1f}')",
        "    print(f'  local contrast     : p5 {s[\"local_contrast_p5\"]:.1f}  median {s[\"local_contrast_median\"]:.1f} grey levels')",
        "    print()",
    ),
    code(
        "print(f\"{'category':<12}{'long side':>10}{'output':>12}{'MP':>7}{'p5 thin':>9}{'<1px':>8}   verdict\")",
        "print('-' * 70)",
        "for r in reports:",
        "    for v in r.resolution_aspect:",
        "        print(f'{r.category:<12}{v.long_side:>10}{v.out_width}x{v.out_height:<8}'",
        "              f'{v.megapixels:>6.2f}{v.p5_min_extent_after:>8.2f}p{v.frac_regions_below_1px:>7.1%}   {v.verdict}')",
        "    d = r.recommended",
        "    print(f'{\"\":<12} -> {\"TILING REQUIRED\" if d.requires_tiling else d.chosen.long_side}')",
        "    print(f'{\"\":<12}    {d.rationale}')",
        "    print()",
    ),
    md(
        "### The cost of a blind square resize",
        "",
        "Shown separately because `resize(256, 256)` is the reflex, and on a non-square",
        "frame it squashes one axis harder than the other. A defect's thin dimension is",
        "hit by whichever axis is squashed hardest, so the damage is worse than the",
        "megapixel count suggests.",
    ),
    code(
        "for r in reports:",
        "    a = {v.long_side: v for v in r.resolution_aspect}",
        "    s = {v.long_side: v for v in r.resolution_square}",
        "    print(f'=== {r.category} ===')",
        "    print(f\"{'long':>6}{'aspect p5':>12}{'square p5':>12}{'aspect MP':>11}{'square MP':>11}\")",
        "    for k in sorted(set(a) & set(s)):",
        "        print(f'{k:>6}{a[k].p5_min_extent_after:>11.2f}p{s[k].p5_min_extent_after:>11.2f}p'",
        "              f'{a[k].megapixels:>11.2f}{s[k].megapixels:>11.2f}')",
        "    print()",
    ),
    md(
        "## 6. Visual check of the defect population",
        "",
        "Always look at the data before trusting a statistic about it. A contact sheet",
        "catches a mask misalignment or an empty ground truth that no percentile would.",
    ),
    code(
        "import matplotlib.pyplot as plt",
        "import numpy as np",
        "from inspector.data.transforms import load_image, load_mask",
        "from inspector.data.core import ANOMALOUS",
        "",
        "fig, axes = plt.subplots(len(CATEGORIES), 4, figsize=(13, 3.4 * len(CATEGORIES)))",
        "for row, cat in enumerate(CATEGORIES):",
        "    anomalous = indices[cat]['test'].filter(label=ANOMALOUS)",
        "    for col in range(4):",
        "        sample = anomalous[col * max(1, len(anomalous) // 4)]",
        "        image = load_image(sample.image_path)",
        "        mask = load_mask(sample.mask_path)",
        "        overlay = image.copy()",
        "        overlay[mask] = (0.45 * overlay[mask] + 0.55 * np.array([255, 40, 40])).astype('uint8')",
        "        ax = axes[row, col]",
        "        ax.imshow(overlay)",
        "        ax.set_title(f'{cat}  defect {mask.mean():.3%} of frame', fontsize=8)",
        "        ax.axis('off')",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 7. Tier 0 floors",
        "",
        "Four models whose job is to fail, and to prove the metric code is right before",
        "anything expensive runs (Gate G2):",
        "",
        "* `random` must land at image AUROC ~0.5 and AU-PRO@L ~L/2. If it does not, the",
        "  metric is broken and every later number is wrong.",
        "* `mean_intensity` / `histogram` reveal a category separable by exposure alone.",
        "  If one of them scores well, a deep model's success there measures the lighting.",
        "* `pixel_pca` is the honest floor for the autoencoder: a conv AE that cannot beat",
        "  linear PCA on raw pixels has learned nothing a linear projection did not.",
    ),
    code(
        "import tempfile",
        "from inspector.data.transforms import ImageTransform",
        "from inspector.models import build_model",
        "from inspector.pipeline import run_experiment",
        "from inspector.results import append_results, render_markdown",
        "from inspector.utils.seed import seed_everything",
        "",
        "RESOLUTION = 256   # revise from the section-5 table if it says otherwise",
        "SEEDS = [0, 1, 2]",
        "transform = ImageTransform(mode='aspect_preserving', long_side=RESOLUTION)",
        "",
        "tier0 = []",
        "for cat in CATEGORIES:",
        "    for name in ['random', 'mean_intensity', 'histogram', 'pixel_pca']:",
        "        for seed in SEEDS:",
        "            seed_everything(seed)",
        "            model = build_model(name, transform, seed=seed)",
        "            with tempfile.TemporaryDirectory() as tmp:",
        "                res = run_experiment(model, indices[cat], workdir=tmp, seed=seed,",
        "                                     test_split='test')",
        "            tier0.append(res)",
        "    print(f'{cat} done')",
        "",
        "append_results(tier0, REPO / 'reports' / 'results_visa.csv')",
        "print(render_markdown(tier0))",
    ),
    code(
        "# Gate G2: the control must be at chance. Averaged over seeds and categories,",
        "# because a single 200-image split still has meaningful variance.",
        "import statistics",
        "",
        "rnd = [r for r in tier0 if r.method == 'random']",
        "print(f'random pixel AUROC   : {statistics.mean(r.pixel_auroc for r in rnd):.4f}  (expect 0.500)')",
        "print(f'random AU-PRO@0.05   : {statistics.mean(r.aupro_005 for r in rnd):.4f}  (expect 0.025)')",
        "print(f'random AU-PRO@0.30   : {statistics.mean(r.aupro_030 for r in rnd):.4f}  (expect 0.150)')",
        "print()",
        "for cat in CATEGORIES:",
        "    trivial = [r for r in tier0 if r.category == cat and r.method in ('mean_intensity', 'histogram')]",
        "    best = max(r.image_auroc for r in trivial)",
        "    flag = '  <-- SEPARABLE BY A GLOBAL STATISTIC, report this prominently' if best > 0.8 else ''",
        "    print(f'{cat:<12} best trivial image AUROC {best:.3f}{flag}')",
    ),
    md(
        "## 8. PatchCore on the laptop",
        "",
        "Fits inside 4 GB at 256² with `resnet18` and a 1% coreset. This is the",
        "development configuration, not the reported one — the WideResNet50-2 reference",
        "config and the ablation sweep belong on Kaggle.",
        "",
        "There is no training here at all: a forward pass over the normal images, then a",
        "coreset. That is why PatchCore is the right upgrade target — no training noise",
        "to confound an ablation.",
    ),
    code(
        "import time, torch",
        "",
        "laptop_runs = []",
        "for cat in CATEGORIES:",
        "    seed_everything(0)",
        "    if torch.cuda.is_available():",
        "        torch.cuda.reset_peak_memory_stats()",
        "    model = build_model('patchcore', transform, seed=0,",
        "                        backbone='resnet18', layers=('layer2', 'layer3'),",
        "                        coreset_ratio=0.01, batch_size=4, k=1)",
        "    t0 = time.perf_counter()",
        "    with tempfile.TemporaryDirectory() as tmp:",
        "        res = run_experiment(model, indices[cat], workdir=tmp, seed=0, test_split='test')",
        "    laptop_runs.append(res)",
        "    print(res.summary())",
        "    print('   ', {k: v for k, v in res.fit_extra.items()",
        "                 if k in ('memory_bank_size', 'memory_bank_mb', 'peak_vram_mb', 'feature_grid')})",
        "",
        "append_results(laptop_runs, REPO / 'reports' / 'results_visa.csv')",
    ),
    code(
        "print(render_markdown(tier0 + laptop_runs))",
    ),
    md(
        "## 9. Qualitative check",
        "",
        "The number and the picture must agree. A high AU-PRO with heatmaps that light up",
        "the background means the metric is being satisfied by something other than the",
        "defect, and that is worth knowing before the sweep runs.",
    ),
    code(
        "cat = CATEGORIES[0]",
        "seed_everything(0)",
        "model = build_model('patchcore', transform, seed=0, backbone='resnet18',",
        "                    coreset_ratio=0.01, batch_size=4)",
        "model.fit(indices[cat]['train'])",
        "",
        "anomalous = indices[cat]['test'].filter(label=ANOMALOUS)",
        "picks = [anomalous[i] for i in range(0, len(anomalous), max(1, len(anomalous) // 4))][:4]",
        "",
        "fig, axes = plt.subplots(3, len(picks), figsize=(3.2 * len(picks), 9))",
        "for col, sample in enumerate(picks):",
        "    image = load_image(sample.image_path)",
        "    mask = load_mask(sample.mask_path)",
        "    pred = model.predict_sample(sample)",
        "    axes[0, col].imshow(image);            axes[0, col].set_title('input', fontsize=9)",
        "    axes[1, col].imshow(mask, cmap='gray'); axes[1, col].set_title('ground truth', fontsize=9)",
        "    axes[2, col].imshow(image)",
        "    axes[2, col].imshow(pred.anomaly_map, cmap='inferno', alpha=0.55)",
        "    axes[2, col].set_title(f'score {pred.score:.3f}', fontsize=9)",
        "    for row in range(3):",
        "        axes[row, col].axis('off')",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 10. Hand-off to Kaggle",
        "",
        "What stays here: acquisition, audit, EDA, Tier 0, and development-scale",
        "PatchCore. What moves to `02_kaggle_experiments.ipynb`:",
        "",
        "| workload | why not here |",
        "|---|---|",
        "| PatchCore with WideResNet50-2 at 320-512² | exceeds 4 GB |",
        "| The ablation sweep (backbone x layers x resolution x coreset) | tens of GPU-hours |",
        "| Autoencoder training, 3 seeds x 3 losses | hours of training |",
        "| Robustness grid | 6 corruptions x 5 severities x 3 categories |",
        "",
        "Record what this notebook produced in the compute ledger, then open notebook 02.",
    ),
    code(
        "ledger = REPO / 'reports' / 'compute_ledger.md'",
        "ledger.parent.mkdir(parents=True, exist_ok=True)",
        "with open(ledger, 'a', encoding='utf-8') as fh:",
        "    fh.write(f'\\n## laptop session\\n')",
        "    fh.write(f'- categories: {CATEGORIES}\\n')",
        "    fh.write(f'- tier0 runs: {len(tier0)}, patchcore runs: {len(laptop_runs)}\\n')",
        "    fh.write(f'- resolution: {RESOLUTION}, backbone: resnet18\\n')",
        "print('appended to', ledger)",
    ),
]


# ===========================================================================
# 02 — Kaggle: full experiments on a 16 GB GPU
# ===========================================================================

KAGGLE = [
    md(
        "# 02 — Full experiments (Kaggle GPU)",
        "",
        "Runs the workloads that do not fit the 4 GB laptop: the PatchCore reference",
        "configuration, the ablation sweep, autoencoder training, and the robustness grid.",
        "",
        "**Kaggle settings**",
        "",
        "| setting | value |",
        "|---|---|",
        "| Accelerator | GPU P100 (16 GB) — or T4 x2 |",
        "| Internet | **On** (needed to fetch VisA and the package) |",
        "| Session limit | 12 h interactive, ~9 h on commit |",
        "| Weekly quota | ~30 GPU-hours |",
        "| Working dir | 20 GB, `/kaggle/working` |",
        "",
        "**Discipline (docs/04 §2).** This notebook is a thin driver: it installs the",
        "package and calls its API. No model code lives in a cell. Every stage",
        "checkpoints to `/kaggle/working`, because the session can die at any moment and",
        "a sweep that cannot resume is a sweep that gets run twice.",
        "",
        "Dataset: **VisA** (Amazon), CC BY 4.0 — see [ATTRIBUTION.md](../ATTRIBUTION.md).",
    ),
    md("## 0. Environment and package"),
    code(
        "import os, sys, subprocess, pathlib, json, time",
        "",
        "ON_KAGGLE = pathlib.Path('/kaggle').exists()",
        "WORK = pathlib.Path('/kaggle/working') if ON_KAGGLE else pathlib.Path.cwd() / 'kaggle_local'",
        "WORK.mkdir(parents=True, exist_ok=True)",
        "print('kaggle    :', ON_KAGGLE)",
        "print('working   :', WORK)",
        "",
        "import torch",
        "print('torch     :', torch.__version__, '| cuda:', torch.cuda.is_available())",
        "if torch.cuda.is_available():",
        "    p = torch.cuda.get_device_properties(0)",
        "    print('gpu       :', p.name, f'{p.total_memory / 1024**3:.1f} GB')",
    ),
    md(
        "### Getting the package onto Kaggle",
        "",
        "Three routes, in order of preference. Set `REPO_URL` if the repository is",
        "pushed; otherwise attach it as a Kaggle dataset (Add Data -> Upload).",
    ),
    code(
        "REPO_URL = ''   # e.g. 'https://github.com/<user>/mvtec-visual-inspector'",
        "PKG_DATASET = '/kaggle/input/mvtec-visual-inspector'  # if uploaded as a dataset",
        "",
        "def install_package():",
        "    if REPO_URL:",
        "        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',",
        "                        f'git+{REPO_URL}'], check=True)",
        "        return 'pip install from git'",
        "    if pathlib.Path(PKG_DATASET).exists():",
        "        sys.path.insert(0, str(pathlib.Path(PKG_DATASET) / 'src'))",
        "        return f'sys.path from {PKG_DATASET}'",
        "    local = pathlib.Path.cwd()",
        "    for candidate in (local, local.parent):",
        "        if (candidate / 'src' / 'inspector').exists():",
        "            sys.path.insert(0, str(candidate / 'src'))",
        "            return f'sys.path from {candidate}'",
        "    raise RuntimeError(",
        "        'inspector package not found. Set REPO_URL, or attach the repo as a '",
        "        'Kaggle dataset at ' + PKG_DATASET)",
        "",
        "print(install_package())",
        "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',",
        "                'opencv-python-headless', 'scikit-image'], check=False)",
        "",
        "from inspector.utils.env import capture",
        "env = capture()",
        "print('git       :', env['git_sha'], '(dirty)' if env['dirty'] else '(clean)')",
    ),
    md(
        "## 1. Data",
        "",
        "Either attach VisA as a Kaggle dataset, or download it here (1.8 GB, needs",
        "Internet on). The download path re-verifies its SHA-256 manifest, which is what",
        "makes a silently truncated transfer detectable.",
    ),
    code(
        "from inspector.fetch import fetch",
        "",
        "VISA_INPUT = pathlib.Path('/kaggle/input/visa-anomaly/VisA_20220922')",
        "if VISA_INPUT.exists():",
        "    VISA_ROOT = VISA_INPUT",
        "    print('using attached dataset:', VISA_ROOT)",
        "else:",
        "    def progress(done, total):",
        "        pct = int(100 * done / total) if total else 0",
        "        if pct % 10 == 0 and done % (200 << 20) < (1 << 20):",
        "            print(f'  {pct:3d}%  {done / 1e9:.2f} / {total / 1e9:.2f} GB')",
        "    manifest = fetch('visa', WORK / 'data', extract=True, progress=progress)",
        "    VISA_ROOT = pathlib.Path(manifest.extracted_to)",
        "    print('downloaded to:', VISA_ROOT)",
        "",
        "assert (VISA_ROOT / 'split_csv' / '1cls.csv').exists(), 'official split CSV missing'",
    ),
    code(
        "from inspector.data import ensure_validation, load_category",
        "from inspector.data.integrity import audit",
        "",
        "CATEGORIES = ['pcb1', 'macaroni2', 'capsules']",
        "indices = {}",
        "for cat in CATEGORIES:",
        "    idx = load_category(VISA_ROOT, cat, layout='visa')",
        "    idx, _ = ensure_validation(idx, val_fraction=0.15, seed=0)",
        "    indices[cat] = idx",
        "    ok = all(r.ok for r in audit(idx))",
        "    print(f'{cat:<11} ' + '  '.join(f'{k}={len(v)}' for k, v in sorted(idx.items())),",
        "          '| integrity', 'OK' if ok else 'FAILED')",
        "    assert ok, f'{cat}: split integrity failed'",
    ),
    md(
        "## 2. Resumable experiment runner",
        "",
        "Every completed run is appended to a JSONL checkpoint keyed by its",
        "configuration. A restarted session skips what is already done. Without this a",
        "12-hour session limit turns a sweep into a gamble.",
    ),
    code(
        "import tempfile",
        "from inspector.data.transforms import ImageTransform",
        "from inspector.models import build_model",
        "from inspector.pipeline import run_experiment",
        "from inspector.results import append_results, render_markdown",
        "from inspector.utils.seed import seed_everything",
        "",
        "CHECKPOINT = WORK / 'runs.jsonl'",
        "RESULTS_CSV = WORK / 'results_visa.csv'",
        "",
        "def done_keys():",
        "    if not CHECKPOINT.exists():",
        "        return set()",
        "    with open(CHECKPOINT, encoding='utf-8') as fh:",
        "        return {json.loads(line)['key'] for line in fh if line.strip()}",
        "",
        "def execute(key, category, model_name, seed, resolution, **kwargs):",
        "    \"\"\"Run one configuration unless the checkpoint says it is already done.\"\"\"",
        "    if key in done_keys():",
        "        print(f'  skip (done): {key}')",
        "        return None",
        "    seed_everything(seed)",
        "    if torch.cuda.is_available():",
        "        torch.cuda.reset_peak_memory_stats()",
        "    transform = ImageTransform(mode='aspect_preserving', long_side=resolution)",
        "    model = build_model(model_name, transform, seed=seed, **kwargs)",
        "    started = time.perf_counter()",
        "    with tempfile.TemporaryDirectory() as tmp:",
        "        result = run_experiment(model, indices[category], workdir=tmp,",
        "                                seed=seed, test_split='test')",
        "    result.notes = key",
        "    append_results([result], RESULTS_CSV)",
        "    with open(CHECKPOINT, 'a', encoding='utf-8') as fh:",
        "        fh.write(json.dumps({'key': key, 'elapsed_s': round(time.perf_counter() - started, 1),",
        "                             'image_auroc': result.image_auroc,",
        "                             'aupro_005': result.aupro_005}) + '\\n')",
        "    print(f'  {key}\\n    {result.summary()}')",
        "    return result",
    ),
    md(
        "## 3. PatchCore reference configuration",
        "",
        "WideResNet50-2, `layer2 + layer3`, 3x3 aggregation, 1% greedy coreset, k=1.",
        "This is the row every ablation is measured against, so it is frozen and run with",
        "3 seeds — the coreset start point is random, so a single run reports noise as",
        "signal.",
    ),
    code(
        "REFERENCE = dict(backbone='wide_resnet50_2', layers=('layer2', 'layer3'),",
        "                 patch_pool=3, projection_dim=1024, coreset_ratio=0.01,",
        "                 k=1, batch_size=8)",
        "RESOLUTION = 320",
        "SEEDS = [0, 1, 2]",
        "",
        "reference_runs = []",
        "for cat in CATEGORIES:",
        "    for seed in SEEDS:",
        "        key = f'ref|{cat}|{RESOLUTION}|s{seed}'",
        "        r = execute(key, cat, 'patchcore', seed, RESOLUTION, **REFERENCE)",
        "        if r:",
        "            reference_runs.append(r)",
    ),
    code(
        "import statistics",
        "",
        "print(f\"{'category':<12}{'I-AUROC':>18}{'AU-PRO@0.05':>20}{'SegF1':>16}\")",
        "print('-' * 66)",
        "for cat in CATEGORIES:",
        "    rows = [r for r in reference_runs if r.category == cat]",
        "    if len(rows) < 2:",
        "        continue",
        "    def ms(attr):",
        "        vals = [getattr(r, attr) for r in rows]",
        "        return f'{statistics.mean(vals):.4f} +/- {statistics.stdev(vals):.4f}'",
        "    print(f'{cat:<12}{ms(\"image_auroc\"):>18}{ms(\"aupro_005\"):>20}{ms(\"segf1_3sigma\"):>16}')",
        "print()",
        "print('Report mean +/- std, never a single seed (protocol section 4.2).')",
    ),
    md(
        "## 4. Ablation sweep — staged, not a grid",
        "",
        "A full grid over backbone x layers x resolution x coreset x k is ~10^4 runs and",
        "is not affordable. A staged sweep varies one axis at a time from the reference,",
        "which captures the main effects in ~60 runs; the one interaction worth having is",
        "re-varied jointly afterwards.",
        "",
        "Single seed during the sweep, then 3 seeds for the winners. Spending 3 seeds on",
        "a configuration that loses by 10 points buys nothing.",
    ),
    code(
        "AXES = {",
        "    'backbone':   [dict(backbone=b) for b in ['resnet18', 'resnet50', 'wide_resnet50_2']],",
        "    'layers':     [dict(layers=l) for l in [('layer2',), ('layer3',),",
        "                                            ('layer2', 'layer3'),",
        "                                            ('layer2', 'layer3', 'layer4')]],",
        "    'coreset':    [dict(coreset_ratio=c) for c in [0.001, 0.01, 0.1, 0.25]],",
        "    'k':          [dict(k=k) for k in [1, 3, 9]],",
        "    'projection': [dict(projection_dim=d) for d in [128, 384, 1024]],",
        "}",
        "RESOLUTIONS = [224, 320, 448]",
        "",
        "planned = sum(len(v) for v in AXES.values()) * len(CATEGORIES) + len(RESOLUTIONS) * len(CATEGORIES)",
        "print(f'planned runs: {planned}  (single seed)')",
        "print('At roughly 1-3 min each on a P100, budget accordingly against the 30 h/week quota.')",
    ),
    code(
        "sweep = []",
        "for axis, variants in AXES.items():",
        "    print(f'=== axis: {axis} ===')",
        "    for variant in variants:",
        "        label = ','.join(f'{k}={v}' for k, v in variant.items())",
        "        for cat in CATEGORIES:",
        "            cfg = {**REFERENCE, **variant}",
        "            r = execute(f'{axis}|{label}|{cat}|{RESOLUTION}|s0', cat,",
        "                        'patchcore', 0, RESOLUTION, **cfg)",
        "            if r:",
        "                sweep.append((axis, label, r))",
    ),
    code(
        "print('=== axis: resolution ===')",
        "for res in RESOLUTIONS:",
        "    for cat in CATEGORIES:",
        "        r = execute(f'resolution|{res}|{cat}|s0', cat, 'patchcore', 0, res, **REFERENCE)",
        "        if r:",
        "            sweep.append(('resolution', str(res), r))",
    ),
    code(
        "# Effect of each axis, averaged over categories, against the reference.",
        "baseline = {r.category: r for r in reference_runs if r.seed == 0}",
        "",
        "print(f\"{'axis':<12}{'variant':<34}{'d AU-PRO@0.05':>15}{'d I-AUROC':>12}\")",
        "print('-' * 74)",
        "from collections import defaultdict",
        "grouped = defaultdict(list)",
        "for axis, label, r in sweep:",
        "    if r.category in baseline:",
        "        grouped[(axis, label)].append((r.aupro_005 - baseline[r.category].aupro_005,",
        "                                       r.image_auroc - baseline[r.category].image_auroc))",
        "for (axis, label), deltas in grouped.items():",
        "    d_pro = statistics.mean(d[0] for d in deltas)",
        "    d_auc = statistics.mean(d[1] for d in deltas)",
        "    print(f'{axis:<12}{label:<34}{d_pro:>+15.4f}{d_auc:>+12.4f}')",
    ),
    md(
        "### Adoption decision (DR-1)",
        "",
        "A change is adopted only if it improves AU-PRO@0.05 on at least 2 of 3",
        "categories, does not regress the third by more than 1 point, passes a paired",
        "test after Holm-Bonferroni correction, and stays inside the latency and VRAM",
        "budgets. Fill the verdict column at the time of the run, not afterwards.",
    ),
    code(
        "from inspector.stats import compare_models, holm_bonferroni",
        "",
        "# Paired over categories here; with per-image AUPIMO available this becomes a",
        "# per-image paired test, which has far more power. Recorded as a limitation.",
        "family = len(grouped)",
        "print(f'family size for the correction: {family}')",
        "print()",
        "for (axis, label), deltas in sorted(grouped.items(), key=lambda kv: -statistics.mean(d[0] for d in kv[1])):",
        "    improved = sum(1 for d in deltas if d[0] > 0)",
        "    worst = min(d[0] for d in deltas)",
        "    verdict = 'adopt' if (improved >= 2 and worst > -0.01) else 'reject'",
        "    print(f'{axis:<12}{label:<34}improved {improved}/{len(deltas)}  worst {worst:+.4f}  -> {verdict}')",
    ),
    md(
        "## 5. Tier 1 — autoencoder baseline",
        "",
        "The scope's required from-scratch baseline. Its purpose is to quantify what the",
        "pretrained prior in PatchCore is actually worth, in points, on this data.",
        "",
        "The L2-vs-SSIM comparison is the instructive part: L2 blurs, and a blurry",
        "reconstruction produces error everywhere rather than at the defect.",
    ),
    code(
        "AE_CONFIGS = [",
        "    dict(loss='l2',      latent_dim=128, residual='multiscale'),",
        "    dict(loss='ssim',    latent_dim=128, residual='multiscale'),",
        "    dict(loss='l2+ssim', latent_dim=128, residual='multiscale'),",
        "    dict(loss='ssim',    latent_dim=32,  residual='multiscale'),",
        "    dict(loss='ssim',    latent_dim=128, residual='raw'),",
        "]",
        "",
        "ae_runs = []",
        "for cfg in AE_CONFIGS:",
        "    label = ','.join(f'{k}={v}' for k, v in cfg.items())",
        "    for cat in CATEGORIES:",
        "        for seed in SEEDS:",
        "            r = execute(f'ae|{label}|{cat}|s{seed}', cat, 'cae', seed, 256,",
        "                        epochs=80, batch_size=16, early_stopping_patience=15, **cfg)",
        "            if r:",
        "                ae_runs.append(r)",
    ),
    code(
        "print(f\"{'config':<40}{'I-AUROC':>10}{'AU-PRO@0.05':>14}{'P-AUROC':>10}\")",
        "print('-' * 74)",
        "by_config = defaultdict(list)",
        "for r in ae_runs:",
        "    by_config[r.notes.split('|')[1]].append(r)",
        "for label, rows in by_config.items():",
        "    print(f'{label:<40}{statistics.mean(r.image_auroc for r in rows):>10.4f}'",
        "          f'{statistics.mean(r.aupro_005 for r in rows):>14.4f}'",
        "          f'{statistics.mean(r.pixel_auroc for r in rows):>10.4f}')",
    ),
    md(
        "### What the pretrained prior bought",
        "",
        "The comparison the whole ladder exists to make. Report it in points, and report",
        "it per category — where the two disagree, that disagreement *is* the finding.",
    ),
    code(
        "best_ae = {}",
        "for cat in CATEGORIES:",
        "    rows = [r for r in ae_runs if r.category == cat]",
        "    if rows:",
        "        best_ae[cat] = max(rows, key=lambda r: r.aupro_005)",
        "",
        "print(f\"{'category':<12}{'best AE':>12}{'PatchCore':>12}{'delta':>10}\")",
        "print('-' * 46)",
        "for cat in CATEGORIES:",
        "    if cat in best_ae and cat in baseline:",
        "        a, p = best_ae[cat].aupro_005, baseline[cat].aupro_005",
        "        print(f'{cat:<12}{a:>12.4f}{p:>12.4f}{p - a:>+10.4f}')",
    ),
    md(
        "## 6. Robustness",
        "",
        "The model is fitted once on clean data and **never re-thresholded**. Corrupting",
        "the test set and then re-tuning the threshold would answer a different and much",
        "easier question.",
        "",
        "The number to watch is not the AUROC drop. It is the **realized false-alarm rate",
        "at the frozen threshold**: a model can hold its AUROC while its alarm rate goes",
        "from 1% to 30%, because the whole score distribution shifted. Ranking survives;",
        "the product does not.",
        "",
        "> The corruption suite ([docs/05](../docs/05-robustness-protocol.md)) is specified",
        "> but not yet implemented — it is Phase P7. This section is the harness; fill it",
        "> in when `inspector.robustness` lands.",
    ),
    code(
        "try:",
        "    from inspector.robustness import CORRUPTIONS, apply_corruption",
        "    HAVE_ROBUSTNESS = True",
        "except ImportError:",
        "    HAVE_ROBUSTNESS = False",
        "    print('inspector.robustness not implemented yet (Phase P7).')",
        "    print('Specification: docs/05-robustness-protocol.md')",
        "    print()",
        "    print('Planned grid: 6 corruption families x 5 severities x 3 categories x 3 models')",
        "    print('             = 270 inference-only evaluations, reusing the fitted models.')",
    ),
    md(
        "## 7. Persist everything before the session dies",
        "",
        "Kaggle discards `/kaggle/working` when the session ends unless the notebook is",
        "committed or the outputs are saved. Download `results_visa.csv` and `runs.jsonl`,",
        "then merge them into the repository's `reports/`.",
    ),
    code(
        "import shutil",
        "",
        "print('results :', RESULTS_CSV, RESULTS_CSV.exists())",
        "print('runs    :', CHECKPOINT, CHECKPOINT.exists())",
        "if CHECKPOINT.exists():",
        "    with open(CHECKPOINT, encoding='utf-8') as fh:",
        "        rows = [json.loads(line) for line in fh if line.strip()]",
        "    total = sum(r['elapsed_s'] for r in rows)",
        "    print(f'completed runs : {len(rows)}')",
        "    print(f'gpu time       : {total / 3600:.2f} h  of the ~30 h weekly quota')",
        "",
        "summary = WORK / 'session_summary.md'",
        "with open(summary, 'w', encoding='utf-8') as fh:",
        "    fh.write('# Kaggle session\\n\\n')",
        "    fh.write(f'- categories: {CATEGORIES}\\n')",
        "    fh.write(f'- reference resolution: {RESOLUTION}\\n')",
        "    fh.write(f'- completed runs: {len(rows) if CHECKPOINT.exists() else 0}\\n')",
        "    fh.write(f'- gpu hours: {total / 3600:.2f}\\n' if CHECKPOINT.exists() else '')",
        "    fh.write('\\nData: VisA (c) Amazon, CC BY 4.0. No images redistributed.\\n')",
        "print('\\nwrote', summary)",
    ),
    code(
        "# The full table. Every caption obligation from docs/02 is satisfied by",
        "# render_markdown: split, threshold source, and oracle marking.",
        "all_runs = reference_runs + [r for _, _, r in sweep] + ae_runs",
        "print(render_markdown(all_runs))",
    ),
]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    targets = [
        ("01_laptop_data_and_eda.ipynb", notebook(LAPTOP, accelerator="gpu")),
        ("02_kaggle_experiments.ipynb", notebook(KAGGLE, accelerator="gpu")),
    ]
    for name, nb in targets:
        path = OUT_DIR / name
        path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
        n_code = sum(1 for c in nb["cells"] if c["cell_type"] == "code")
        print(f"wrote {path}  ({len(nb['cells'])} cells, {n_code} code)")


if __name__ == "__main__":
    main()
