"""Generate the project notebooks.

Notebooks are *generated* rather than hand-edited for the same reason the results
table is: a notebook that is edited in place accumulates hidden state, stale
outputs and cells that only ran once in an order nobody recorded. Regenerating
from this script guarantees the committed notebooks are exactly what the source
says, with no execution counts or outputs baked in.

    python scripts/build_notebooks.py

Both notebooks are **thin drivers** (docs/06 §1): they install the package and
call its API. No model code lives in a cell, because code in a notebook cannot
be tested, reviewed, or re-run six weeks later.
"""

from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[1] / "notebooks"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines) -> list[str]:
    text = "\n".join(lines)
    out = text.splitlines(keepends=True)
    return out or [""]


def notebook(cells: list[dict], *, accelerator: str = "none") -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
            "accelerator": "GPU" if accelerator == "gpu" else "None",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


# ===========================================================================
# 01 — laptop: acquisition, audit, EDA, Tier 0
# ===========================================================================

LAPTOP = [
    md(
        "# 01 — Data acquisition, audit and exploratory analysis (laptop)",
        "",
        "Runs on the RTX 3050 laptop (4 GB VRAM). Everything here is either CPU-bound or",
        "small enough to fit the card. The heavy sweeps live in `02_kaggle_experiments.ipynb`.",
        "",
        "**What this notebook decides:** the input resolution for the study. That single",
        "choice determines whether the experiments measure the *method* or measure the",
        "*resize* — see [docs/10-datasets.md](../docs/10-datasets.md) and",
        "[docs/01-charter-and-protocol.md](../docs/01-charter-and-protocol.md) §4.1.",
        "",
        "**Order matters.** Fit is never called before the split audit passes. A leaked",
        "split does not raise an error, it produces a *better* score, so it has to be",
        "ruled out mechanically before any number is generated.",
        "",
        "---",
        "",
        "Dataset: **VisA** (Amazon), CC BY 4.0. No images are redistributed by this",
        "repository. Attribution in [ATTRIBUTION.md](../ATTRIBUTION.md).",
    ),
    md("## 0. Environment"),
    code(
        "import sys, pathlib",
        "",
        "REPO = pathlib.Path.cwd()",
        "if not (REPO / 'src' / 'inspector').exists():",
        "    REPO = REPO.parent  # running from notebooks/",
        "sys.path.insert(0, str(REPO / 'src'))",
        "",
        "from inspector.utils.env import capture",
        "",
        "env = capture()",
        "print('git      :', env['git_sha'], '(dirty)' if env['dirty'] else '(clean)')",
        "print('device   :', env['device'].get('gpu_name', 'CPU only'),",
        "      f\"{env['device'].get('gpu_total_mb', 0)} MB\")",
        "print('torch    :', env['libraries'].get('torch', 'not installed'))",
        "print()",
        "print('A dirty tree tags every run dirty, and dirty runs may not enter the')",
        "print('headline table (docs/06 section 2). Commit before a reportable run.')",
    ),
    md(
        "## 1. Acquire VisA",
        "",
        "1.93 GB over HTTPS, no account. The fetch records a SHA-256 manifest so a",
        "silently truncated or updated archive is detected rather than trained on.",
    ),
    code(
        "from inspector.fetch import fetch, verify",
        "",
        "DATA_RAW = REPO / 'data' / 'raw'",
        "manifest = fetch('visa', DATA_RAW, extract=True)",
        "",
        "VISA_ROOT = pathlib.Path(manifest.extracted_to)",
        "print('root     :', VISA_ROOT)",
        "print('action   :', manifest.action)",
        "for name, digest in manifest.files.items():",
        "    print(f'  {name:26s} sha256={digest[:16]}')",
        "print()",
        "print('license  :', manifest.license_note)",
    ),
    code(
        "# Re-run this after any sync to Drive or Kaggle. Sync corruption is silent,",
        "# and finding it a week later costs a week.",
        "for name, ok in verify('visa', DATA_RAW).items():",
        "    print(f\"  {'OK  ' if ok else 'FAIL'} {name}\")",
    ),
    md(
        "## 2. The official one-class split",
        "",
        "`split_csv/1cls.csv` is authoritative. Inventing a split would produce numbers",
        "comparable with nothing, so the loader treats a missing CSV as an error rather",
        "than falling back on directory scanning.",
    ),
    code(
        "from inspector.data.visa import summarize",
        "from inspector.postproc import min_achievable_fpr",
        "",
        "counts = summarize(VISA_ROOT)",
        "print(f\"{'category':<13}{'group':<20}{'train':>7}{'test_N':>8}{'test_A':>8}\"",
        "      f\"{'val@15%':>9}{'minFPR':>8}\")",
        "print('-' * 73)",
        "for cat, c in counts.items():",
        "    n_val = max(4, round(c['train_normal'] * 0.15))",
        "    print(f\"{cat:<13}{c['group']:<20}{c['train_normal']:>7}{c['test_normal']:>8}\"",
        "          f\"{c['test_anomaly']:>8}{n_val:>9}{min_achievable_fpr(n_val):>7.2%}\")",
    ),
    md(
        "### Read the `minFPR` column",
        "",
        "A threshold set as the k-th largest of `n` validation scores is exceeded by a",
        "fresh normal sample with probability `k/(n+1)`, so the achievable false-alarm",
        "floor is `1/(n+1)` — see [ADR-7](../docs/07-risks-and-decisions.md).",
        "",
        "On VisA that floor lands **on both sides of 1%**: the large categories",
        "(`candle`, `macaroni*`, `pcb*`) can be calibrated to 1%, the small ones",
        "(`cashew`, `fryum`, `chewinggum`, `pipe_fryum`) cannot. The same protocol is",
        "therefore achievable on some categories and not others *within one dataset*,",
        "which is why the operating point is reported per category rather than as one",
        "headline FPR.",
        "",
        "The floor depends on the 15% carve fraction, which is our choice, not VisA's.",
        "Raising it buys a lower floor at the cost of training images — an ablation worth",
        "running rather than a default worth assuming.",
    ),
    md(
        "## 3. Study categories",
        "",
        "One from each of VisA's three structural groups, so each fails for a different",
        "reason. Three PCBs would test one difficulty three times.",
        "",
        "| category | group | axis it stresses |",
        "|---|---|---|",
        "| `pcb1` | complex structure | resolution / small defects |",
        "| `macaroni2` | multiple instances | false positives from normal variation |",
        "| `capsules` | multiple instances | optics: transparent, reflective |",
    ),
    code(
        "CATEGORIES = ['pcb1', 'macaroni2', 'capsules']",
        "CONTROL = 'cashew'  # easiest group; a method that fails here is broken",
        "",
        "from inspector.data import ensure_validation, load_category",
        "",
        "indices = {}",
        "for cat in CATEGORIES:",
        "    idx = load_category(VISA_ROOT, cat, layout='visa')",
        "    idx, assignment = ensure_validation(idx, val_fraction=0.15, seed=0)",
        "    indices[cat] = idx",
        "    print(f'{cat:<11} ' + '  '.join(",
        "        f'{k}={len(v)}(N{v.n_normal}/A{v.n_anomalous})' for k, v in sorted(idx.items())))",
        "    if assignment:",
        "        print(f'{\"\":<11} validation carved from train, seed={assignment.seed} '",
        "              f'digest={assignment.digest[:12]}')",
    ),
    md(
        "## 4. Split integrity — run before anything is fitted",
        "",
        "Protocol rules L1-L7. L1 compares SHA-256 of file **bytes**, not filenames: the",
        "failure mode that matters is the same capture appearing in two splits under",
        "different names, which a filename check would miss entirely.",
    ),
    code(
        "from inspector.data.integrity import audit",
        "",
        "all_ok = True",
        "for cat, idx in indices.items():",
        "    print(f'--- {cat} ---')",
        "    for report in audit(idx):",
        "        print(' ', report)",
        "        all_ok &= report.ok",
        "",
        "assert all_ok, 'split integrity failed: fix before generating any number'",
        "print('\\nall integrity checks passed')",
    ),
    md(
        "## 5. Exploratory analysis — the resolution decision",
        "",
        "Measures every connected defect region, then computes what each candidate",
        "resolution does to the **smallest** defects. The percentiles matter more than",
        "the median here: the median defect is rarely the one a model misses.",
    ),
    code(
        "from inspector.eda import analyse_category",
        "from inspector.report import write_eda_report",
        "",
        "CANDIDATES = (128, 224, 256, 320, 448, 512)",
        "reports = []",
        "for cat, idx in indices.items():",
        "    print(f'analysing {cat} ...')",
        "    reports.append(analyse_category(idx, test_split='test', candidates=CANDIDATES))",
        "",
        "md_path, json_path = write_eda_report(reports, REPO / 'reports' / 'eda_visa')",
        "print('\\nreport ->', md_path)",
    ),
    code(
        "for r in reports:",
        "    s = r.region_summary",
        "    print(f'=== {r.category}  native {r.native_size[0]}x{r.native_size[1]} '",
        "          f'({r.aspect_ratio:.2f}:1) ===')",
        "    print(f'  regions            : {int(s[\"n_regions\"])} over {int(s[\"n_images\"])} images')",
        "    print(f'  area %% of image    : p1 {s[\"area_fraction_p1\"]:.4%}  '",
        "          f'median {s[\"area_fraction_median\"]:.4%}  max {s[\"area_fraction_max\"]:.3%}')",
        "    print(f'  thin dimension px  : p1 {s[\"min_extent_p1\"]:.1f}  median {s[\"min_extent_median\"]:.1f}')",
        "    print(f'  local contrast     : p5 {s[\"local_contrast_p5\"]:.1f}  median {s[\"local_contrast_median\"]:.1f} grey levels')",
        "    print()",
    ),
    code(
        "print(f\"{'category':<12}{'long side':>10}{'output':>12}{'MP':>7}{'p5 thin':>9}{'<1px':>8}   verdict\")",
        "print('-' * 70)",
        "for r in reports:",
        "    for v in r.resolution_aspect:",
        "        print(f'{r.category:<12}{v.long_side:>10}{v.out_width}x{v.out_height:<8}'",
        "              f'{v.megapixels:>6.2f}{v.p5_min_extent_after:>8.2f}p{v.frac_regions_below_1px:>7.1%}   {v.verdict}')",
        "    d = r.recommended",
        "    print(f'{\"\":<12} -> {\"TILING REQUIRED\" if d.requires_tiling else d.chosen.long_side}')",
        "    print(f'{\"\":<12}    {d.rationale}')",
        "    print()",
    ),
    md(
        "### The cost of a blind square resize",
        "",
        "Shown separately because `resize(256, 256)` is the reflex, and on a non-square",
        "frame it squashes one axis harder than the other. A defect's thin dimension is",
        "hit by whichever axis is squashed hardest, so the damage is worse than the",
        "megapixel count suggests.",
    ),
    code(
        "for r in reports:",
        "    a = {v.long_side: v for v in r.resolution_aspect}",
        "    s = {v.long_side: v for v in r.resolution_square}",
        "    print(f'=== {r.category} ===')",
        "    print(f\"{'long':>6}{'aspect p5':>12}{'square p5':>12}{'aspect MP':>11}{'square MP':>11}\")",
        "    for k in sorted(set(a) & set(s)):",
        "        print(f'{k:>6}{a[k].p5_min_extent_after:>11.2f}p{s[k].p5_min_extent_after:>11.2f}p'",
        "              f'{a[k].megapixels:>11.2f}{s[k].megapixels:>11.2f}')",
        "    print()",
    ),
    md(
        "## 6. Visual check of the defect population",
        "",
        "Always look at the data before trusting a statistic about it. A contact sheet",
        "catches a mask misalignment or an empty ground truth that no percentile would.",
    ),
    code(
        "import matplotlib.pyplot as plt",
        "import numpy as np",
        "from inspector.data.transforms import load_image, load_mask",
        "from inspector.data.core import ANOMALOUS",
        "",
        "fig, axes = plt.subplots(len(CATEGORIES), 4, figsize=(13, 3.4 * len(CATEGORIES)))",
        "for row, cat in enumerate(CATEGORIES):",
        "    anomalous = indices[cat]['test'].filter(label=ANOMALOUS)",
        "    for col in range(4):",
        "        sample = anomalous[col * max(1, len(anomalous) // 4)]",
        "        image = load_image(sample.image_path)",
        "        mask = load_mask(sample.mask_path)",
        "        overlay = image.copy()",
        "        overlay[mask] = (0.45 * overlay[mask] + 0.55 * np.array([255, 40, 40])).astype('uint8')",
        "        ax = axes[row, col]",
        "        ax.imshow(overlay)",
        "        ax.set_title(f'{cat}  defect {mask.mean():.3%} of frame', fontsize=8)",
        "        ax.axis('off')",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 7. Tier 0 floors",
        "",
        "Four models whose job is to fail, and to prove the metric code is right before",
        "anything expensive runs (Gate G2):",
        "",
        "* `random` must land at image AUROC ~0.5 and AU-PRO@L ~L/2. If it does not, the",
        "  metric is broken and every later number is wrong.",
        "* `mean_intensity` / `histogram` reveal a category separable by exposure alone.",
        "  If one of them scores well, a deep model's success there measures the lighting.",
        "* `pixel_pca` is the honest floor for the autoencoder: a conv AE that cannot beat",
        "  linear PCA on raw pixels has learned nothing a linear projection did not.",
    ),
    code(
        "# Every run goes through the shared runner (docs/13, F04): a fully resolved",
        "# spec, a run_id covering every effective setting, provenance, and a registry",
        "# that a restarted session reloads instead of recomputing.",
        "from inspector.config import deep_merge, load_config",
        "from inspector.results import render_markdown, write_results",
        "from inspector.runner import Registry, execute, prepare",
        "",
        "REGISTRY = Registry(REPO / 'reports' / 'runs')",
        "# One common resolution for every method: the controlled comparison (E01).",
        "COMMON = {'preprocess': {'long_side': 320}}",
        "base_cfg = deep_merge(load_config(REPO / 'configs' / 'data' / 'visa_pcb1.yaml'), COMMON)",
        "",
        "def run(cfg, method, category, seed):",
        "    spec, model, idx = prepare(cfg, method=method, category=category, seed=seed,",
        "                               data_root=VISA_ROOT)",
        "    result, reused = execute(spec, model, idx, data_root=VISA_ROOT, registry=REGISTRY)",
        "    print(('reused ' if reused else 'ran    ') + f'[{spec.run_id}] ' + result.summary())",
        "    return result",
        "",
        "tier0 = []",
        "for cat in CATEGORIES:",
        "    # random is stochastic: 3 seeds. The others are deterministic, and rerunning",
        "    # them would only manufacture an artificial standard deviation.",
        "    tier0 += [run(base_cfg, 'random', cat, s) for s in (0, 1, 2)]",
        "    tier0 += [run(base_cfg, m, cat, 0) for m in ('mean_intensity', 'histogram', 'pixel_pca')]",
        "",
        "print(render_markdown(tier0))",
    ),
    code(
        "# Gate G2: the control must be at chance. Averaged over seeds and categories,",
        "# because a single 200-image split still has meaningful variance.",
        "import statistics",
        "",
        "rnd = [r for r in tier0 if r.method == 'random']",
        "print(f'random pixel AUROC   : {statistics.mean(r.pixel_auroc for r in rnd):.4f}  (expect 0.500)')",
        "print(f'random AU-PRO@0.05   : {statistics.mean(r.aupro_005 for r in rnd):.4f}  (expect 0.025)')",
        "print(f'random AU-PRO@0.30   : {statistics.mean(r.aupro_030 for r in rnd):.4f}  (expect 0.150)')",
        "print()",
        "for cat in CATEGORIES:",
        "    trivial = [r for r in tier0 if r.category == cat and r.method in ('mean_intensity', 'histogram')]",
        "    best = max(r.image_auroc for r in trivial)",
        "    flag = '  <-- SEPARABLE BY A GLOBAL STATISTIC, report this prominently' if best > 0.8 else ''",
        "    print(f'{cat:<12} best trivial image AUROC {best:.3f}{flag}')",
    ),
    md(
        "## 8. PatchCore on the laptop",
        "",
        "There is no training here at all: a forward pass over the normal images, then a",
        "coreset. That is why PatchCore is the right upgrade target — no training noise",
        "to confound an ablation.",
        "",
        "### Choosing the resolution — and which resource actually binds",
        "",
        "Measured on this card (WideResNet50-2, `layer2+layer3`), a **native-resolution",
        "forward pass costs under 1 GB of VRAM at batch 1**. VRAM is not the constraint.",
        "",
        "What binds is the **patch matrix in host RAM**. A `layer2` grid at 1404 x 1070",
        "yields 23,584 patches per image, so 768 training images produce 18.1 M patches —",
        "37 GB in fp16, beyond this laptop and a Kaggle session alike. The cell below",
        "computes the largest resolution whose patch matrix fits the RAM actually free,",
        "rather than assuming one.",
        "",
        "The model now samples candidates **per image during extraction**",
        "(`candidate_fraction`, docs/13 F07), so the matrix above is never materialized;",
        "what remains resident is the candidate pool. The cell below sizes that pool",
        "against the RAM actually free. At a reduced resolution some defect regions are",
        "attenuated below one input pixel — §5's table says what fraction — which is why",
        "resolution is a study axis (E04/E05), not a setting.",
    ),
    code(
        "import psutil",
        "",
        "available_gb = psutil.virtual_memory().available / 1e9",
        "budget_gb = available_gb * 0.45      # leave room for the OS and the scoring pass",
        "n_train = max(len(indices[c]['train']) for c in CATEGORIES)",
        "",
        "print(f'host RAM available : {available_gb:.1f} GB   budget {budget_gb:.1f} GB')",
        "print(f'largest train split: {n_train} images')",
        "print()",
        "CANDIDATE_FRACTION = 0.1",
        "print(f\"{'long side':>10}{'patches/img':>13}{'all patches':>13}{'candidates GB':>15}  fits?\")",
        "chosen = None",
        "for long_side in (256, 320, 448, 512, 704, 1024):",
        "    w, h = long_side, round(long_side * 1070 / 1404)",
        "    per_img = (w // 8) * (h // 8)",
        "    total = per_img * n_train",
        "    gb = total * CANDIDATE_FRACTION * 1024 * 2 / 1e9",
        "    fits = gb < budget_gb",
        "    if fits:",
        "        chosen = long_side",
        "    print(f'{long_side:>10}{per_img:>13,}{total:>13,}{gb:>15.2f}  {\"yes\" if fits else \"NO\"}')",
        "",
        "print(f'\\n-> largest resolution whose candidate pool fits: {chosen}')",
        "print('   The E01 comparison still runs every method at 320 so the table is controlled;')",
        "print('   higher resolutions belong to the E04 memory/resolution study.')",
    ),
    code(
        "pc_cfg = deep_merge(base_cfg, load_config(REPO / 'configs' / 'models' / 'patchcore.yaml'))",
        "patchcore = [run(pc_cfg, 'patchcore', cat, s) for cat in CATEGORIES for s in (0, 1, 2)]",
        "print(render_markdown(tier0 + patchcore))",
        "",
        "for r in patchcore[:1]:",
        "    print({k: r.fit_extra.get(k) for k in ('patches_total', 'candidate_count', 'bank_requested',",
        "                                          'bank_effective', 'bank_capped', 'fit_peak_vram_mb')})",
    ),
    code(
        "# The whole registry, regenerated — never hand-edited.",
        "table = write_results(REGISTRY.results(), REPO / 'reports' / 'results_registry.csv')",
        "print('registry table ->', table)",
    ),
    md(
        "## 9. Qualitative check",
        "",
        "The number and the picture must agree. A high AU-PRO with heatmaps that light up",
        "the background means the metric is being satisfied by something other than the",
        "defect, and that is worth knowing before the sweep runs.",
    ),
    code(
        "# Drawn from the STORED predictions of the registry run — no refit. One fixed",
        "# colour scale for every panel: stretching each heatmap independently makes a",
        "# normal image look as anomalous as a defective one (docs/13 §12).",
        "from inspector.models.base import postprocess_map",
        "",
        "cat = CATEGORIES[0]",
        "run0 = next(r for r in patchcore if r.category == cat and r.seed == 0)",
        "test_preds = REGISTRY.load_predictions(run0.run_id, 'test', root=VISA_ROOT)",
        "vmax = float(np.quantile(np.concatenate([m.ravel() for m in test_preds.raw_maps]), 0.999))",
        "",
        "anomalous = [i for i, y in enumerate(test_preds.labels) if y == 1]",
        "normal = [i for i, y in enumerate(test_preds.labels) if y == 0]",
        "picks = anomalous[::max(1, len(anomalous) // 3)][:3] + normal[:1]",
        "",
        "fig, axes = plt.subplots(3, len(picks), figsize=(3.2 * len(picks), 9))",
        "for col, i in enumerate(picks):",
        "    image = load_image(VISA_ROOT / test_preds.ids[i])",
        "    mask = next(m for k, m in enumerate(test_preds.masks()) if k == i)",
        "    amap = postprocess_map(test_preds.raw_maps[i], input_size=test_preds.input_sizes[i],",
        "                           native_size=test_preds.native_sizes[i], sigma=4.0)",
        "    kind = 'defect' if test_preds.labels[i] else 'NORMAL'",
        "    axes[0, col].imshow(image); axes[0, col].set_title(f'{kind}', fontsize=9)",
        "    axes[1, col].imshow(mask, cmap='gray'); axes[1, col].set_title('ground truth', fontsize=9)",
        "    axes[2, col].imshow(image)",
        "    axes[2, col].imshow(amap, cmap='inferno', alpha=0.55, vmin=0, vmax=vmax)",
        "    axes[2, col].set_title(f'score {test_preds.scores[i]:.3f}', fontsize=9)",
        "    for row in range(3):",
        "        axes[row, col].axis('off')",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 9b. Studies on stored predictions (E02, E03, E02b)",
        "",
        "No refits: every number below comes from the registry's stored scores and raw",
        "maps. The study separates three questions the headline table mixes together —",
        "",
        "* **E02** — is the image score (map-to-scalar rule) the bottleneck, rather than",
        "  the map? Maps are fixed, so localization cannot move.",
        "* **E03** — how much of the operating point is the rule, and how much is the",
        "  calibration draw? Plus two exchangeability checks: the *bulk* (shift AUROC)",
        "  and the *upper tail* (exact permutation test), because a rank threshold",
        "  depends only on the tail.",
        "* **E02b** — does restricting the image score to the object region, estimated",
        "  from training normals only, remove background nuisance? Margins are",
        "  pre-declared and all are reported; the defect-coverage column is a safety",
        "  check that chose nothing.",
    ),
    code(
        "from inspector.analysis import render_studies, run_studies",
        "from IPython.display import Markdown, display",
        "",
        "study = run_studies(REGISTRY.root, methods=['random', 'pixel_pca', 'patchcore'],",
        "                    data_root=VISA_ROOT, roi_methods=('patchcore',), draws=200)",
        "display(Markdown(render_studies(study)))",
    ),
    md(
        "## 10. Hand-off to Kaggle",
        "",
        "What stays here: acquisition, audit, EDA, Tier 0, the PatchCore reference at",
        "320 px, and every study on stored predictions. What moves to",
        "`02_kaggle_experiments.ipynb`:",
        "",
        "| workload | why not here |",
        "|---|---|",
        "| The ablation screen (backbone x layers x resolution x bank x neighbours) | ~20 GPU-hours |",
        "| PatchCore at 448 px and above | host RAM for the candidate pool, not VRAM |",
        "| Autoencoder variants, 5 x 3 categories x 3 seeds | hours of training |",
        "| Robustness grid | corruptions x 5 severities x 3 categories, one fit each |",
        "",
        "Record what this notebook produced in the compute ledger, then open notebook 02.",
    ),
    code(
        "ledger = REPO / 'reports' / 'compute_ledger.md'",
        "ledger.parent.mkdir(parents=True, exist_ok=True)",
        "with open(ledger, 'a', encoding='utf-8') as fh:",
        "    fh.write(f'\\n## laptop session\\n')",
        "    fh.write(f'- categories: {CATEGORIES}\\n')",
        "    fh.write(f'- tier0 runs: {len(tier0)}, patchcore runs: {len(patchcore)}\\n')",
        "    fh.write('- common resolution: 320 (E01 controlled comparison)\\n')",
        "print('appended to', ledger)",
    ),
]


# ===========================================================================
# 02 — Kaggle: full experiments on a 16 GB GPU
# ===========================================================================

KAGGLE = [
    md(
        "# 02 — Full experiments (Kaggle GPU)",
        "",
        "Runs the workloads that do not fit the 4 GB laptop: the PatchCore reference",
        "configuration, the ablation sweep, autoencoder training, and the robustness grid.",
        "",
        "**Kaggle settings**",
        "",
        "| setting | value |",
        "|---|---|",
        "| Accelerator | GPU P100 (16 GB) — or T4 x2 |",
        "| Internet | **On** (needed to fetch VisA and the package) |",
        "| Session limit | 12 h interactive, ~9 h on commit |",
        "| Weekly quota | ~30 GPU-hours |",
        "| Working dir | 20 GB, `/kaggle/working` |",
        "",
        "**Discipline (docs/04 §2).** This notebook is a thin driver: it installs the",
        "package and calls its API. No model code lives in a cell. Every stage",
        "checkpoints to `/kaggle/working`, because the session can die at any moment and",
        "a sweep that cannot resume is a sweep that gets run twice.",
        "",
        "Dataset: **VisA** (Amazon), CC BY 4.0 — see [ATTRIBUTION.md](../ATTRIBUTION.md).",
    ),
    md("## 0. Environment and package"),
    code(
        "import os, sys, subprocess, pathlib, json",
        "",
        "ON_KAGGLE = pathlib.Path('/kaggle').exists()",
        "WORK = pathlib.Path('/kaggle/working') if ON_KAGGLE else pathlib.Path.cwd() / 'kaggle_local'",
        "WORK.mkdir(parents=True, exist_ok=True)",
        "print('kaggle    :', ON_KAGGLE)",
        "print('working   :', WORK)",
        "",
        "import torch",
        "print('torch     :', torch.__version__, '| cuda:', torch.cuda.is_available())",
        "if torch.cuda.is_available():",
        "    p = torch.cuda.get_device_properties(0)",
        "    print('gpu       :', p.name, f'{p.total_memory / 1024**3:.1f} GB')",
    ),
    md(
        "### Getting the package onto Kaggle",
        "",
        "The notebook needs a checkout, not just the package: run configurations live",
        "in `configs/`. In order of preference: a local checkout (when run on the",
        "laptop), the repository attached as a Kaggle dataset (Add Data -> Upload), or a",
        "shallow clone of `REPO_URL` (needs Internet on). Pin a commit with `REPO_REF`",
        "for a run you intend to report.",
        "",
        "Only missing packages are installed. Upgrading numpy or torch inside a running",
        "Kaggle kernel leaves it with mismatched binaries.",
    ),
    code(
        "REPO_URL = 'https://github.com/ThanhDatVN/MVTec-Visual-Inspector.git'",
        "REPO_REF = ''   # a commit sha or tag; empty = default branch head",
        "PKG_DATASET = pathlib.Path('/kaggle/input/mvtec-visual-inspector')",
        "",
        "def locate_repo():",
        "    for candidate in (pathlib.Path.cwd(), pathlib.Path.cwd().parent, PKG_DATASET):",
        "        if (candidate / 'src' / 'inspector').exists() and (candidate / 'configs').exists():",
        "            return candidate",
        "    clone = WORK / 'mvi'",
        "    if not clone.exists():",
        "        subprocess.run(['git', 'clone', '--depth', '50', REPO_URL, str(clone)], check=True)",
        "        if REPO_REF:",
        "            subprocess.run(['git', '-C', str(clone), 'checkout', REPO_REF], check=True)",
        "    return clone",
        "",
        "REPO = locate_repo()",
        "sys.path.insert(0, str(REPO / 'src'))",
        "os.chdir(REPO)  # provenance records the git sha of the working directory",
        "print('repo      :', REPO)",
        "",
        "import importlib.util",
        "missing = [pip_name for mod, pip_name in [('cv2', 'opencv-python-headless'), ('yaml', 'pyyaml')]",
        "           if importlib.util.find_spec(mod) is None]",
        "if missing:",
        "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', *missing], check=True)",
        "",
        "from inspector.utils.env import capture",
        "env = capture()",
        "print('git       :', env['git_sha'], '(dirty)' if env['dirty'] else '(clean)')",
    ),
    md(
        "## 1. Data",
        "",
        "Either attach VisA as a Kaggle dataset, or download it here (1.8 GB, needs",
        "Internet on). The download path re-verifies its SHA-256 manifest, which is what",
        "makes a silently truncated transfer detectable.",
    ),
    code(
        "from inspector.fetch import fetch",
        "",
        "VISA_INPUT = pathlib.Path('/kaggle/input/visa-anomaly/VisA_20220922')",
        "if VISA_INPUT.exists():",
        "    VISA_ROOT = VISA_INPUT",
        "    print('using attached dataset:', VISA_ROOT)",
        "else:",
        "    def progress(done, total):",
        "        pct = int(100 * done / total) if total else 0",
        "        if pct % 10 == 0 and done % (200 << 20) < (1 << 20):",
        "            print(f'  {pct:3d}%  {done / 1e9:.2f} / {total / 1e9:.2f} GB')",
        "    manifest = fetch('visa', WORK / 'data', extract=True, progress=progress)",
        "    VISA_ROOT = pathlib.Path(manifest.extracted_to)",
        "    print('downloaded to:', VISA_ROOT)",
        "",
        "assert (VISA_ROOT / 'split_csv' / '1cls.csv').exists(), 'official split CSV missing'",
    ),
    code(
        "from inspector.data import ensure_validation, load_category",
        "from inspector.data.integrity import audit",
        "",
        "CATEGORIES = ['pcb1', 'macaroni2', 'capsules']",
        "indices = {}",
        "for cat in CATEGORIES:",
        "    idx = load_category(VISA_ROOT, cat, layout='visa')",
        "    idx, _ = ensure_validation(idx, val_fraction=0.15, seed=0)",
        "    indices[cat] = idx",
        "    ok = all(r.ok for r in audit(idx))",
        "    print(f'{cat:<11} ' + '  '.join(f'{k}={len(v)}' for k, v in sorted(idx.items())),",
        "          '| integrity', 'OK' if ok else 'FAILED')",
        "    assert ok, f'{cat}: split integrity failed'",
    ),
    md(
        "## 2. The shared runner",
        "",
        "Every run goes through `inspector.runner` — the same code path as the CLI and",
        "the laptop notebook. A run's identity is a hash of everything that can change",
        "its numbers: the split listing, the model's *effective* hyperparameters",
        "(defaults included), the transform, the evaluation settings, the seed, and a",
        "hash of the package source. A restarted session reuses completed runs and",
        "reloads their results, so the summary tables below always cover the whole",
        "registry, not just what ran in this session (docs/13, F04).",
        "",
        "A failed run leaves a `failed` record with its reason instead of vanishing.",
    ),
    code(
        "from collections import defaultdict",
        "import statistics",
        "",
        "from inspector.config import deep_merge, load_config",
        "from inspector.results import render_markdown, write_results",
        "from inspector.runner import Registry, execute, prepare",
        "",
        "REGISTRY = Registry(WORK / 'runs')",
        "RESULTS_CSV = WORK / 'results_registry.csv'",
        "",
        "data_cfg = load_config(REPO / 'configs' / 'data' / 'visa_pcb1.yaml')",
        "PATCHCORE_CFG = deep_merge(data_cfg, load_config(REPO / 'configs' / 'models' / 'patchcore.yaml'))",
        "CAE_CFG = deep_merge(data_cfg, load_config(REPO / 'configs' / 'models' / 'cae.yaml'))",
        "",
        "def run(cfg, method, category, seed, **overrides):",
        "    \"\"\"One run through the shared runner; reused if already in the registry.\"\"\"",
        "    spec, model, idx = prepare(cfg, method=method, category=category, seed=seed,",
        "                               data_root=VISA_ROOT, overrides=overrides or None)",
        "    if torch.cuda.is_available():",
        "        torch.cuda.reset_peak_memory_stats()",
        "    try:",
        "        result, reused = execute(spec, model, idx, data_root=VISA_ROOT, registry=REGISTRY)",
        "    except Exception as exc:  # recorded as a failed run by execute; keep the sweep going",
        "        print(f'  FAILED [{spec.run_id}] {category} {overrides}: {exc}')",
        "        return None",
        "    finally:",
        "        del model",
        "        if torch.cuda.is_available():",
        "            torch.cuda.empty_cache()",
        "    print(('  reused ' if reused else '  ran    ') + f'[{spec.run_id}] ' + result.summary())",
        "    return result",
    ),
    md(
        "## 3. PatchCore reference configuration",
        "",
        "`configs/models/patchcore.yaml`: WideResNet50-2, `layer2 + layer3`, 3x3",
        "aggregation, adaptive channel pooling to 1024, per-image candidate sampling",
        "(10%), a 1% greedy coreset selected in a 128-d random projection, nearest-",
        "neighbour patch scores and the reference re-weighting of the image score.",
        "This is the row every ablation is measured against, so it is run with 3 seeds —",
        "candidate sampling and the coreset start point are random.",
    ),
    code(
        "RESOLUTION = 320",
        "SEEDS = [0, 1, 2]",
        "",
        "reference_runs = [r for cat in CATEGORIES for s in SEEDS",
        "                  if (r := run(PATCHCORE_CFG, 'patchcore', cat, s)) is not None]",
    ),
    code(
        "print(f\"{'category':<12}{'I-AUROC':>20}{'AU-PRO@0.05':>20}{'FPR@OP1':>18}\")",
        "print('-' * 70)",
        "for cat in CATEGORIES:",
        "    rows = [r for r in reference_runs if r.category == cat]",
        "    if len(rows) < 2:",
        "        continue",
        "    def ms(attr):",
        "        vals = [getattr(r, attr) for r in rows]",
        "        return f'{statistics.mean(vals):.4f} +/- {statistics.stdev(vals):.4f}'",
        "    print(f'{cat:<12}{ms(\"image_auroc\"):>20}{ms(\"aupro_005\"):>20}{ms(\"fpr_at_op1\"):>18}')",
        "print()",
        "print('Report mean +/- std over seeds, never a single seed (protocol section 4.2).')",
        "print('FPR@OP1 is the realized test false-alarm rate at the conservative validation')",
        "print('threshold; compare it with the effective bound in the registry table.')",
    ),
    md(
        "## 4. Ablation sweep — staged, not a grid",
        "",
        "A full grid over backbone x layers x resolution x bank x neighbours is ~10^4",
        "runs and is not affordable. A staged sweep varies one axis at a time from the",
        "reference. Single seed during the sweep, then 3 seeds for anything that looks",
        "like a winner — spending 3 seeds on a configuration that loses by 10 points buys",
        "nothing.",
        "",
        "Two axes are coupled to other parameters, and varying them naively measures",
        "nothing (docs/13):",
        "",
        "- **neighbours.** With `patch_reduction='nearest'` the patch score is the",
        "  nearest distance whatever `patch_neighbors` is, so a k sweep must pair k with",
        "  `mean` or `kth` reduction (F02).",
        "- **bank size.** The coreset is selected from the per-image candidates, so a",
        "  bank ratio above `candidate_fraction` is silently capped (F08). The bank axis",
        "  runs with a larger candidate pool, and the registry records",
        "  `bank_requested`, `bank_effective` and `bank_capped` for every run.",
    ),
    code(
        "AXES = {",
        "    'backbone':   [dict(backbone=b) for b in ['resnet18', 'resnet50']],",
        "    'layers':     [dict(layers=l) for l in [['layer2'], ['layer3'],",
        "                                            ['layer2', 'layer3', 'layer4']]],",
        "    'bank':       [dict(bank_ratio=r, candidate_fraction=0.25)",
        "                   for r in [0.001, 0.01, 0.05, 0.1]],",
        "    'neighbours': [dict(patch_neighbors=k, patch_reduction=red)",
        "                   for k, red in [(3, 'mean'), (9, 'mean'), (3, 'kth')]],",
        "    'reweight':   [dict(reweight=False)],",
        "    'projection': [dict(projection_dim=d) for d in [256, 512]],",
        "}",
        "RESOLUTIONS = [224, 448]",
        "",
        "planned = (sum(len(v) for v in AXES.values()) + len(RESOLUTIONS)) * len(CATEGORIES)",
        "print(f'planned runs: {planned}  (single seed, reference excluded)')",
        "print('Budget against the ~30 GPU-hour weekly quota; the registry makes it resumable.')",
    ),
    code(
        "sweep = []",
        "for axis, variants in AXES.items():",
        "    print(f'=== axis: {axis} ===')",
        "    for variant in variants:",
        "        label = ','.join(f'{k}={v}' for k, v in variant.items())",
        "        for cat in CATEGORIES:",
        "            r = run(PATCHCORE_CFG, 'patchcore', cat, 0, **variant)",
        "            if r is not None:",
        "                sweep.append((axis, label, r))",
        "",
        "print('=== axis: resolution ===')",
        "for res in RESOLUTIONS:",
        "    cfg = deep_merge(PATCHCORE_CFG, {'preprocess': {'long_side': res}})",
        "    for cat in CATEGORIES:",
        "        r = run(cfg, 'patchcore', cat, 0)",
        "        if r is not None:",
        "            sweep.append(('resolution', str(res), r))",
    ),
    code(
        "# Effect of each variant against the seed-0 reference of the same category.",
        "baseline = {r.category: r for r in reference_runs if r.seed == 0}",
        "",
        "print(f\"{'axis':<12}{'variant':<46}{'d AU-PRO@0.05':>15}{'d I-AUROC':>12}\")",
        "print('-' * 86)",
        "grouped = defaultdict(list)",
        "for axis, label, r in sweep:",
        "    if r.category in baseline:",
        "        b = baseline[r.category]",
        "        grouped[(axis, label)].append((r.aupro_005 - b.aupro_005, r.image_auroc - b.image_auroc))",
        "for (axis, label), deltas in grouped.items():",
        "    d_pro = statistics.mean(d[0] for d in deltas)",
        "    d_auc = statistics.mean(d[1] for d in deltas)",
        "    print(f'{axis:<12}{label:<46}{d_pro:>+15.4f}{d_auc:>+12.4f}')",
    ),
    md(
        "### Screening, not adoption",
        "",
        "With three categories and one seed, the sweep can only *screen*: it says which",
        "variants are worth three seeds and a paired test. The rule below flags",
        "candidates; adoption (DR-1) needs the 3-seed rerun, a paired per-image bootstrap",
        "(`inspector.stats.paired_bootstrap_difference`) with Holm correction over the",
        "family of variants tested, and a latency/VRAM check. The same variant must then",
        "hold on the frozen confirmation categories before it is reported as an",
        "improvement (docs/13, ADR-10).",
    ),
    code(
        "print(f'family size for the correction: {len(grouped)}')",
        "print()",
        "order = sorted(grouped.items(), key=lambda kv: -statistics.mean(d[0] for d in kv[1]))",
        "for (axis, label), deltas in order:",
        "    improved = sum(1 for d in deltas if d[0] > 0)",
        "    worst = min(d[0] for d in deltas)",
        "    flag = 'candidate' if (improved >= 2 and worst > -0.01) else '-'",
        "    print(f'{axis:<12}{label:<46}improved {improved}/{len(deltas)}  worst {worst:+.4f}  {flag}')",
    ),
    md(
        "## 5. Tier 1 — autoencoder baseline",
        "",
        "The scope's required from-scratch baseline. Its purpose is to quantify what the",
        "pretrained prior in PatchCore is worth, in points, on this data.",
        "",
        "The L2-vs-SSIM comparison is the instructive part: L2 blurs, and a blurry",
        "reconstruction produces error everywhere rather than at the defect. The AE runs",
        "at the same 320 px long side as PatchCore so the comparison is not also a",
        "resolution comparison.",
    ),
    code(
        "AE_CFG = deep_merge(CAE_CFG, {'preprocess': {'long_side': RESOLUTION}})",
        "AE_VARIANTS = [",
        "    dict(loss='l2'),",
        "    dict(loss='ssim'),",
        "    dict(loss='l2+ssim'),",
        "    dict(loss='ssim', latent_dim=32),",
        "    dict(loss='ssim', residual='raw'),",
        "]",
        "",
        "ae_runs = []",
        "for variant in AE_VARIANTS:",
        "    label = ','.join(f'{k}={v}' for k, v in variant.items())",
        "    print(f'=== {label} ===')",
        "    for cat in CATEGORIES:",
        "        for seed in SEEDS:",
        "            r = run(AE_CFG, 'cae', cat, seed, epochs=80, early_stopping_patience=15, **variant)",
        "            if r is not None:",
        "                ae_runs.append((label, r))",
    ),
    code(
        "print(f\"{'config':<32}{'I-AUROC':>10}{'AU-PRO@0.05':>14}{'P-AUROC':>10}\")",
        "print('-' * 66)",
        "by_config = defaultdict(list)",
        "for label, r in ae_runs:",
        "    by_config[label].append(r)",
        "for label, rows in by_config.items():",
        "    print(f'{label:<32}{statistics.mean(r.image_auroc for r in rows):>10.4f}'",
        "          f'{statistics.mean(r.aupro_005 for r in rows):>14.4f}'",
        "          f'{statistics.mean(r.pixel_auroc for r in rows):>10.4f}')",
    ),
    md(
        "### What the pretrained prior bought",
        "",
        "The comparison the whole ladder exists to make, per category and in points.",
        "The AE configuration is chosen on **validation** loss, not on test AU-PRO:",
        "picking the best of five on the test set and comparing it with PatchCore",
        "would bias the difference in the AE's favour. Here we use the mean over seeds",
        "of each configuration and show all of them; where they disagree, the",
        "disagreement is the finding.",
    ),
    code(
        "print(f\"{'category':<12}{'config':<32}{'AE':>10}{'PatchCore':>12}{'delta':>10}\")",
        "print('-' * 76)",
        "for cat in CATEGORIES:",
        "    pc = [r.aupro_005 for r in reference_runs if r.category == cat]",
        "    if not pc:",
        "        continue",
        "    for label, rows in by_config.items():",
        "        ae = [r.aupro_005 for r in rows if r.category == cat]",
        "        if ae:",
        "            a, p = statistics.mean(ae), statistics.mean(pc)",
        "            print(f'{cat:<12}{label:<32}{a:>10.4f}{p:>12.4f}{p - a:>+10.4f}')",
    ),
    md(
        "## 6. Robustness",
        "",
        "The model is fitted once on clean data and **never re-thresholded**: the image",
        "threshold and the pixel 3-sigma threshold come from the clean validation split,",
        "and only the test split is corrupted. Re-tuning under corruption would answer",
        "a different and much easier question.",
        "",
        "The number to watch is not the AUROC drop. It is the **realized false-alarm rate",
        "at the frozen threshold**: a model can hold its AUROC while its alarm rate goes",
        "from 1% to 30%, because the whole score distribution shifted. Ranking survives;",
        "the product does not. Normal test images are corrupted too — they are the",
        "only images that can show a false alarm.",
        "",
        "Severity is defined relative to each category's **measured median defect",
        "diameter**, so severity 3 means the same physical thing on `pcb1` as on",
        "`capsules`. Every image gets its own corruption seed (a stable hash of its",
        "path), shared across severities, so a severity step changes the strength of",
        "the corruption and not its random pattern. Metrics come from the same",
        "evaluator as every other run (`inspector.evaluate`).",
    ),
    code(
        "import zlib",
        "",
        "import pandas as pd",
        "",
        "from inspector.eda import measure_regions, summarize_regions",
        "from inspector.evaluate import SplitPredictions, evaluate",
        "from inspector.robustness import MAIN_SUITE, SEVERITIES, apply_corruption",
        "from inspector.runner import eval_config_from_config",
        "",
        "print('corruptions :', MAIN_SUITE)",
        "print('severities  :', SEVERITIES)",
        "print('grid        :', len(MAIN_SUITE) * len(SEVERITIES), 'cells per model per category')",
        "",
        "# The scale reference: median defect diameter, per category, in native pixels.",
        "d_med = {}",
        "for cat in CATEGORIES:",
        "    stats = summarize_regions(measure_regions(indices[cat]['test'], with_contrast=False))",
        "    d_med[cat] = stats['diameter_px_median']",
        "    print(f'{cat:<12} median defect diameter {d_med[cat]:.1f} px')",
    ),
    code(
        "ROBUST_CSV = WORK / 'robustness.csv'",
        "EVAL_CFG = eval_config_from_config(PATCHCORE_CFG)",
        "",
        "def corruptor(corruption, severity, cat, root):",
        "    def image_fn(image, mask, sample):",
        "        seed = zlib.crc32(sample.rel_id(root).encode())  # per image, fixed across severities",
        "        return apply_corruption(image, mask, corruption, severity,",
        "                                median_defect_diameter=d_med[cat], seed=seed)",
        "    return image_fn",
        "",
        "robust_rows = pd.read_csv(ROBUST_CSV).to_dict('records') if ROBUST_CSV.exists() else []",
        "done = {(r['category'], r['model'], r['corruption'], r['severity']) for r in robust_rows}",
        "",
        "for cat in CATEGORIES:",
        "    cells = [(c, s) for c in MAIN_SUITE for s in (0, *SEVERITIES)",
        "             if (cat, 'patchcore', c, s) not in done]",
        "    if not cells:",
        "        continue",
        "    spec, model, idx = prepare(PATCHCORE_CFG, method='patchcore', category=cat, seed=0,",
        "                               data_root=VISA_ROOT)",
        "    model.fit(idx['train'])",
        "    val = SplitPredictions.from_model(model, idx['validation'])  # clean, frozen",
        "    test_idx = idx[spec.dataset['test_split']]",
        "    clean = None",
        "    for corruption, severity in cells:",
        "        if severity == 0 and clean is not None:",
        "            test = clean",
        "        else:",
        "            fn = None if severity == 0 else corruptor(corruption, severity, cat, test_idx.root)",
        "            test = SplitPredictions.from_model(model, test_idx, image_fn=fn)",
        "            if severity == 0:",
        "                clean = test",
        "        m = evaluate(val, test, EVAL_CFG)",
        "        robust_rows.append(dict(category=cat, model='patchcore', run_id=spec.run_id,",
        "                                corruption=corruption, severity=severity,",
        "                                image_auroc=m['image_auroc'], aupro_005=m.get('aupro_005'),",
        "                                fpr=m['fpr_at_op1'], recall=m['recall_at_op1'],",
        "                                effective_fpr=m['effective_fpr']))",
        "        pd.DataFrame(robust_rows).to_csv(ROBUST_CSV, index=False)  # resumable per cell",
        "    print(f'  {cat} done ({len(cells)} cells)')",
        "    del model",
        "    if torch.cuda.is_available():",
        "        torch.cuda.empty_cache()",
        "",
        "robust = pd.DataFrame(robust_rows)",
        "print(robust.shape)",
    ),
    code(
        "# The deployment-critical view: the alarm rate at a frozen threshold.",
        "print(f\"{'corruption':<18}{'sev':>4}{'d AUROC':>10}{'FPR':>9}{'FPR x clean':>13}{'recall':>9}\")",
        "print('-' * 64)",
        "for corruption in MAIN_SUITE:",
        "    base = robust[(robust.corruption == corruption) & (robust.severity == 0)]",
        "    for sev in SEVERITIES:",
        "        rows = robust[(robust.corruption == corruption) & (robust.severity == sev)]",
        "        d_auc = rows.image_auroc.mean() - base.image_auroc.mean()",
        "        ratio = rows.fpr.mean() / max(base.fpr.mean(), 1e-6)",
        "        print(f'{corruption:<18}{sev:>4}{d_auc:>+10.4f}{rows.fpr.mean():>9.3f}'",
        "              f'{ratio:>13.1f}x{rows.recall.mean():>9.3f}')",
    ),
    code(
        "# 'Severity at which it breaks': the lowest severity whose realized false-alarm",
        "# rate exceeds 3x its clean value. More actionable than an area-under-degradation",
        "# number, because it converts to a maintenance tolerance. With ~100 normal test",
        "# images one false alarm is 1 point of FPR, so treat single-step changes with care.",
        "print(f\"{'corruption':<18}{'breaks at severity'}\")",
        "print('-' * 40)",
        "for corruption in MAIN_SUITE:",
        "    base = robust[(robust.corruption == corruption) & (robust.severity == 0)].fpr.mean()",
        "    broke = None",
        "    for sev in SEVERITIES:",
        "        f = robust[(robust.corruption == corruption) & (robust.severity == sev)].fpr.mean()",
        "        if f > 3 * max(base, 1e-6):",
        "            broke = sev",
        "            break",
        "    print(f'{corruption:<18}{broke if broke else \"survives all 5\"}')",
    ),
    md(
        "### The validity question",
        "",
        "Synthetic illumination corruption is a *model* of real lighting shift. Whether",
        "it predicts real behaviour is an empirical question, and it can only be answered",
        "on MVTec AD 2, whose `test_private_mixed` split is captured under genuinely",
        "unseen lighting.",
        "",
        "When AD 2 is available, compute the Spearman rank correlation between the model",
        "ranking under `exposure_*` / `spatial_light` and the ranking under the real",
        "shift. High correlation validates synthetic robustness testing as a cheap proxy;",
        "low correlation is a finding about a practice the field relies on.",
    ),
    md(
        "## 7. Persist everything before the session dies",
        "",
        "Kaggle discards `/kaggle/working` when the session ends unless the notebook is",
        "committed or the outputs are saved. The registry directory is the unit to keep:",
        "copy `runs/` into the repository's `reports/runs/` and regenerate the table with",
        "`inspector results`. The `*.maps.npz` files hold raw anomaly maps (derived",
        "data, not dataset images) and are git-ignored; keep them locally for the",
        "aggregation and calibration studies.",
    ),
    code(
        "import shutil",
        "",
        "results = REGISTRY.results()",
        "write_results(results, RESULTS_CSV)",
        "print(f'registry runs : {len(results)}  -> {RESULTS_CSV}')",
        "failed = [p.parent.name for p in (WORK / 'runs').glob('*/result.json')",
        "          if json.loads(p.read_text()).get('status') == 'failed']",
        "print(f'failed runs   : {len(failed)}', failed[:10])",
        "",
        "archive = shutil.make_archive(str(WORK / 'runs_export'), 'zip', WORK / 'runs')",
        "print('archive       :', archive)",
        "",
        "summary = WORK / 'session_summary.md'",
        "with open(summary, 'w', encoding='utf-8') as fh:",
        "    fh.write('# Kaggle session\\n\\n')",
        "    fh.write(f'- categories: {CATEGORIES}\\n')",
        "    fh.write(f'- reference resolution: {RESOLUTION}\\n')",
        "    fh.write(f'- registry runs: {len(results)} (failed: {len(failed)})\\n')",
        "    fh.write(f'- git: {env[\"git_sha\"]}\\n')",
        "    fh.write('\\nData: VisA (c) Amazon, CC BY 4.0. No images redistributed.\\n')",
        "print('wrote', summary)",
    ),
    code(
        "# The full table. Every caption obligation from docs/02 is met by",
        "# render_markdown: split, threshold source, target vs effective FPR, oracle marking.",
        "print(render_markdown(results))",
    ),
]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    targets = [
        ("01_laptop_data_and_eda.ipynb", notebook(LAPTOP, accelerator="gpu")),
        ("02_kaggle_experiments.ipynb", notebook(KAGGLE, accelerator="gpu")),
    ]
    for name, nb in targets:
        path = OUT_DIR / name
        path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
        n_code = sum(1 for c in nb["cells"] if c["cell_type"] == "code")
        print(f"wrote {path}  ({len(nb['cells'])} cells, {n_code} code)")


if __name__ == "__main__":
    main()
